
import { Student } from './types';

// Adding explicit cast as Student[] to prevent the 'tipo' string literal from widening to 'string'
export const INITIAL_STUDENTS: Student[] = ([
  { id: 'al-Agatha', nome: 'Agatha', tipo: 'aluno' },
  { id: 'al-Alicya', nome: 'Alicya', tipo: 'aluno' },
  { id: 'al-AnaCecilia', nome: 'Ana Cecilia', tipo: 'aluno' },
  { id: 'al-AnaClara', nome: 'Ana Clara', tipo: 'aluno' },
  { id: 'al-AnaJulia', nome: 'Ana Julia', tipo: 'aluno' },
  { id: 'al-Arthur', nome: 'Arthur', tipo: 'aluno' },
  { id: 'al-BernardoTorres', nome: 'Bernardo Torres', tipo: 'aluno' },
  { id: 'al-CarlosMiguel', nome: 'Carlos Miguel', tipo: 'aluno' },
  { id: 'al-CarlosPeixinho', nome: 'Carlos Peixinho', tipo: 'aluno' },
  { id: 'al-CarlosVieira', nome: 'Carlos Vieira', tipo: 'aluno' },
  { id: 'al-DaviMenezes', nome: 'Davi Menezes', tipo: 'aluno' },
  { id: 'al-EmanuellePoco', nome: 'Emanuelle Poço', tipo: 'aluno' },
  { id: 'al-ErickSantos', nome: 'Erick Santos', tipo: 'aluno' },
  { id: 'al-FelipeFerreira', nome: 'Felipe Ferreira', tipo: 'aluno' },
  { id: 'al-Gael', nome: 'Gael', tipo: 'aluno' },
  { id: 'al-HeitorAlves', nome: 'Heitor Alves', tipo: 'aluno' },
  { id: 'al-HeitorMorato', nome: 'Heitor Morato', tipo: 'aluno' },
  { id: 'al-Isaac', nome: 'Isaac', tipo: 'aluno' },
  { id: 'al-IsabellyMartins', nome: 'Isabelly Martins', tipo: 'aluno' },
  { id: 'al-JoaoMiguel', nome: 'João Miguel', tipo: 'aluno' },
  { id: 'al-JoaoPedro', nome: 'João Pedro', tipo: 'aluno' },
  { id: 'al-Julia', nome: 'Júlia', tipo: 'aluno' },
  { id: 'al-KauaBrito', nome: 'Kauã Brito', tipo: 'aluno' },
  { id: 'al-Laura', nome: 'Laura', tipo: 'aluno' },
  { id: 'al-Lavinia', nome: 'Lavinia', tipo: 'aluno' },
  { id: 'al-Leonardo', nome: 'Leonardo', tipo: 'aluno' },
  { id: 'al-LeornardoNascimento', nome: 'Leornardo Nascimento', tipo: 'aluno' },
  { id: 'al-Lorenzo', nome: 'Lorenzo', tipo: 'aluno' },
  { id: 'al-LuizMiguel', nome: 'Luiz Miguel', tipo: 'aluno' },
  { id: 'al-Melissa', nome: 'Melissa', tipo: 'aluno' },
  { id: 'al-Miguel', nome: 'Miguel', tipo: 'aluno' },
  { id: 'al-Pedro', nome: 'Pedro', tipo: 'aluno' },
  { id: 'al-Samuel', nome: 'Samuel', tipo: 'aluno' },
  { id: 'al-SophiaAssis', nome: 'Sophia Assis', tipo: 'aluno' },
  { id: 'al-SophiaBernades', nome: 'Sophia Bernades', tipo: 'aluno' },
  { id: 'al-SophiaRodrigues', nome: 'Sophia Rodrigues', tipo: 'aluno' },
  { id: 'al-TeoLima', nome: 'Teo Lima', tipo: 'aluno' },
  { id: 'al-TheoLuccaVieira', nome: 'Theo Lucca Vieira', tipo: 'aluno' },
  { id: 'al-Vinicius', nome: 'Vinicius', tipo: 'aluno' },
  { id: 'al-ViniciusAndrade', nome: 'Vinicius Andrade', tipo: 'aluno' },
  { id: 'al-VitorHugoGoncalves', nome: 'Vitor Hugo Gonçalves', tipo: 'aluno' },
  { id: 'al-Vitoria', nome: 'Vitoria', tipo: 'aluno' },
  { id: 'al-Yasmin', nome: 'Yasmin', tipo: 'aluno' }
] as Student[]).sort((a, b) => a.nome.localeCompare(b.nome, 'pt-BR'));
